swagger: "2.0"
info:
  title: j4n.io
  description: RESTful shortlink service
  version: "v1"
schemes:
  - http
host: j4n.io
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
paths:
  /:
    get:
      security:
       - basicAuth: []
      summary: Retrieve complete list of shortlinks
      parameters:
      - name: api
        in: query
        description: The desired API version, e.g. `v1`, `v2`, etc. Defaults to the latest version.
        required: false
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/shortlink"
    post:
      security:
       - basicAuth: []
      summary: Create shortlink with random token
      parameters:
      - name: api
        in: query
        description: The desired API version, e.g. `v1`, `v2`, etc. Defaults to the latest version.
        required: false
        type: string
      - name: request
        in: body
        schema:
          $ref: '#/definitions/request'
      responses:
        201:
          description: Shortlink was created successfully
          schema:
            $ref: "#/definitions/shortlink"
        400:
          description: Bad request (request body malformed)
          schema:
            $ref: "#/definitions/error"
  /:token:
    get:
      summary: Redirect to deposit URL
      parameters:
      - name: api
        in: query
        description: The desired API version, e.g. `v1`, `v2`, etc. Defaults to the latest version.
        required: false
        type: string
      responses:
        default:
          description: The status code, which was stored for this shortlink
          schema:
            $ref: "#/definitions/shortlink"
    post:
      security:
       - basicAuth: []
      summary: Update shortlink information
      parameters:
      - name: api
        in: query
        description: The desired API version, e.g. `v1`, `v2`, etc. Defaults to the latest version.
        required: false
        type: string
      - name: request
        in: body
        schema:
          $ref: '#/definitions/request'
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/shortlink"
        400:
          description: Bad request (request body malformed)
          schema:
            $ref: "#/definitions/error"
    delete:
      security:
       - basicAuth: []
      summary: Delete shortlink resource
      parameters:
      - name: api
        in: query
        description: The desired API version, e.g. `v1`, `v2`, etc. Defaults to the latest version.
        required: false
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/shortlink"
    put:
      security:
       - basicAuth: []
      summary: Create a new shortlink under this very path
      parameters:
      - name: api
        in: query
        description: The desired API version, e.g. `v1`, `v2`, etc. Defaults to the latest version.
        required: false
        type: string
      - name: request
        in: body
        schema:
          $ref: '#/definitions/request'
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/shortlink"
        400:
          description: Bad request (request body malformed)
          schema:
            $ref: "#/definitions/error"
definitions:
  request:
    type: object
    required:
    - url
    - status_code
    properties:
      url:
        type: string
        description: The URL where the shortlink is about to redirect
      status_code:
        type: integer
        description: The HTTP status code for this shortlink
  shortlink:
    type: object
    properties:
      token:
        type: string
        description: The path under which the shortlink is reachable
      url:
        type: string
        description: The URL where the shortlink is about to redirect
      status_code:
        type: integer
        description: The HTTP status code for this shortlink
      created:
        type: string
        format: date
        description: Timestamp when this shortlink resource was created (ISO 8601)
      updated:
        type: string
        format: date
        description: Timestamp when this shortlink resource was updated the last time (ISO 8601)
  error:
    type: object
    required:
    - message
    - code
    properties:
      message:
        type: string
        description: Human readable error message
      code:
        type: integer
        description: HTTP status code of this error
      details:
        type: array
        items:
          type: string
        description: Detailed information about
