swagger: "2.0"
info:
  title: j4n.io
  description: RESTful shortlink service
  version: "1.0"
schemes:
  - http
host: j4n.io
produces:
  - application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
paths:
  /:
    get:
      security:
       - basicAuth: []
      summary: Retrieve complete list of shortlinks
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/shortlink"
    post:
      security:
       - basicAuth: []
      summary: Create shortlink with random token
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/request'
      responses:
        201:
          description: Shortlink was created successfully
          schema:
            $ref: "#/definitions/shortlink"
  /:token:
    get:
      summary: Redirect to deposit URL
      responses:
        default:
          description: The status code, which was stored for this shortlink
          schema:
            $ref: "#/definitions/shortlink"
    post:
      security:
       - basicAuth: []
      summary: Update shortlink information
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/request'
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/shortlink"
    delete:
      security:
       - basicAuth: []
      summary: Delete shortlink resource
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/shortlink"
    put:
      security:
       - basicAuth: []
      summary: Create a new shortlink under this very path
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/request'
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/shortlink"
definitions:
  request:
    type: object
    properties:
      url:
        type: string
        description: The URL where the shortlink is about to redirect
      status_code:
        type: integer
        description: The HTTP status code for this shortlink
      version:
        type: number
        format: float
        description: The API version
  shortlink:
    type: object
    properties:
      token:
        type: string
        description: The path under which the shortlink is reachable
      url:
        type: string
        description: The URL where the shortlink is about to redirect
      status_code:
        type: integer
        description: The HTTP status code for this shortlink
      created:
        type: string
        format: date
        description: Timestamp when this shortlink resource was created (ISO 8601)
      updated:
        type: string
        format: date
        description: Timestamp when this shortlink resource was updated the last time (ISO 8601)
